<?php return [
    'plugin' => [
        'name' => 'Import themes and plugins',
        'description' => 'Import or replace OctoberCMS themes and plugins',
        'import_theme' => 'Import theme',
        'import_theme_description' => 'Import or replace OctoberCMS theme',
        'import_plugin' => 'Import plugin',
        'import_plugin_description' => 'Import or replace OctoberCMS plugin'
    ],
    'permissions' => [
        'allow_theme_import' => 'Allow themes and plugins import'
    ],
    'backend' => [
        'import' => 'Import theme',
        'import_theme' => 'Import theme',
        'import_plugin' => 'Import plugin',
        'theme_zip' => 'Theme ZIP file',
        'theme_zip_hint' => 'Compressed file with October CMS theme',
        'plugin_zip' => 'Plugin ZIP file',
        'plugin_zip_hint' => 'Compressed file with October CMS plugin',
        'replace_static_pages_content' => 'Replace files generated by Rainlab.Pages plugin',
        'replace_static_pages_content_hint' => 'Turn this on if you want to replace all files generated by Rainlab.Pages plugin, e.g. static pages, static menus, etc.',
        'remove_all_existing_files' => 'Remove all existing files',
        'remove_all_existing_files_hint' => 'Before uploading files all existing files will be removed',
        'yes' => 'Yes',
        'no' => 'No',
        'flash' => [
            'theme_success' => 'Theme successfully imported',
            'plugin_success' => 'Plugin successfully imported',
            'invalid_input' => 'Invalid input',
            'invalid_extension' => 'Invalid extension',
            'could_not_open_zip' => 'Could not open ZIP file',
            'invalid_dir_structure' => 'Invalid directory structure'
        ]
    ],
    'button' => [
        'import' => 'Import'
    ]
];
